In [29]:
import pandas as pd
import numpy  as np
from IPython.display import display

In [37]:
methods = [
  lambda n: np.random.normal(0.0, 1.0, n),
  lambda n: np.random.standard_cauchy(n),
  lambda n: np.random.standard_t(3.0, n),
  lambda n: np.random.poisson(10.0, n),
  lambda n: np.random.uniform(-np.sqrt(3), np.sqrt(3), n)
]

names = ["normal", "cauchy", "student", "poisson", "uniform"]
N = [10, 100, 1000]
repeats = 1000

for i in range(len(methods)):
  for n in N:
    data = np.zeros([2, 5])
    for j in range(repeats):
      sample = methods[i](n)
      
      x = np.mean(sample)
      med_x = np.median(sample)
      z_r = (sample[0] + sample[-1]) / 2.0
      z_q = (sample[int(np.ceil(n / 4.0) - 1)] + sample[int(np.ceil(3.0 * n / 4.0) - 1)]) / 2.0
      r = int(np.round(n / 4.0))
      z_tr = (1.0 / (n - 2 * r)) * sum([sample[i] for i in range(r, n - r)])

      stats = [x, med_x, z_r, z_q, z_tr]
      for k in range(len(stats)):
        data[0][k] += stats[k]
        data[1][k] += stats[k] * stats[k]
    
    data /= repeats
    data[1] -= data[0] ** 2
    df = pd.DataFrame(data, columns=["x", "med x", "z_R", "z_Q", "z_{tr}"], index=["E(z)", "D(z)"])
    print(f"{names[i]} n = {n}")
    display(df)

normal n = 10

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.007406  0.007054 -0.002073 -0.024144  0.006021
D(z)  0.095480  0.129847  0.457127  0.488698  0.158806

normal n = 100

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.000554  0.002732 -0.011512  0.030530  0.002348
D(z)  0.009567  0.014580  0.480881  0.525271  0.019587

normal n = 1000

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.000007  0.000904 -0.010478 -0.006566 -0.000432
D(z)  0.000942  0.001506  0.502017  0.486230  0.001968

cauchy n = 10

                x     med x          z_R           z_Q        z_{tr}
E(z)     2.777845 -0.023830    -0.716097      4.130711      5.298384
D(z)  9353.789584  0.361634  3887.790626  30562.512464  25470.700791

cauchy n = 100

               x     med x         z_R           z_Q      z_{tr}
E(z)    0.212537  0.000053    1.119985      0.650281   -0.446985
D(z)  243.297033  0.025542  622.022015  14923.142617  280.512617

cauchy n = 1000

               x     med x          z_R         z_Q       z_{tr}
E(z)   -0.126266 -0.001088     0.180850   -1.002840    -0.180213
D(z)  566.530441  0.002413  3818.200702  574.433424  1023.226277

student n = 10

             x    med x       z_R       z_Q    z_{tr}
E(z) -0.010638  0.00560  0.008146 -0.042459 -0.029080
D(z)  0.282514  0.17116  1.185425  1.353516  0.526522

student n = 100

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.002546  0.001244  0.041985  0.043052  0.005503
D(z)  0.028638  0.017901  1.682606  2.099226  0.059536

student n = 1000

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.001268 -0.000013 -0.041527  0.042754  0.001638
D(z)  0.003086  0.002052  1.380052  1.649603  0.006000

poisson n = 10

             x   med x       z_R        z_Q    z_{tr}
E(z)  9.966700  9.8100  9.901000  10.039000  9.993667
D(z)  1.141821  1.5729  5.287699   5.708479  1.846515

poisson n = 100

              x     med x        z_R       z_Q    z_{tr}
E(z)  10.006710  9.848000  10.198500  10.04550  9.988320
D(z)   0.107118  0.218396   5.118848   4.94868  0.215432

poisson n = 1000

             x     med x        z_R       z_Q     z_{tr}
E(z)  9.999441  9.997000  10.063000  9.952000  10.001848
D(z)  0.010745  0.002991   4.877531  4.937696   0.020841

uniform n = 10

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.011323  0.022280  0.006929  0.024935  0.011665
D(z)  0.102642  0.239319  0.451519  0.479541  0.176945

uniform n = 100

             x     med x       z_R       z_Q    z_{tr}
E(z) -0.003909 -0.003834  0.015249 -0.004070 -0.008984
D(z)  0.010040  0.028028  0.516198  0.506686  0.020714

uniform n = 1000

             x     med x       z_R       z_Q    z_{tr}
E(z)  0.002601  0.004582  0.019769 -0.025590  0.003502
D(z)  0.001057  0.003175  0.516817  0.537625  0.002035